title:             Cyc1am3n's Blog
email:             kantori321@gmail.com
description:       Welcome to Cyc1am3n's Blog
author:            cyc1am3n
baseurl:           ""
url:               "http://cyc1am3n.github.io"

# Social Profiles
twitter_username:  cyc1am3n
github_username:   cyc1am3n
facebook_username: cyc1am3n

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
encoding: utf-8
highlighter: rouge
