title:             Cyc1am3n's Blog
email:             kantori321@korea.ac.kr
description:       소소한 공부노트
author:            cyc1am3n
baseurl:           ""
url:               "http://cyc1am3n.github.io"

# Social Profiles
github_username:   cyc1am3n
instagram_username: deep_in_deep_learning
disqus_shortname: cyc1am3n

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
encoding: utf-8
highlighter: rouge
